// <auto-generated />
using System;
using DPCS.DAL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DPCS.DAL.Migrations
{
    [DbContext(typeof(DpcsDbContext))]
    [Migration("20260410132525_InitialCreatePgsql")]
    partial class InitialCreatePgsql
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DPCS.DAL.Entities.CrackedPasswordEntity", b =>
                {
                    b.Property<string>("Hash")
                        .HasColumnType("text");

                    b.Property<int>("AttackMode")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CrackedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("HashType")
                        .HasColumnType("integer");

                    b.Property<string>("JobId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Plaintext")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<TimeSpan>("TimeTaken")
                        .HasColumnType("interval");

                    b.HasKey("Hash");

                    b.ToTable("CrackedPasswords");
                });

            modelBuilder.Entity("DPCS.DAL.Entities.JobRecordEntity", b =>
                {
                    b.Property<string>("JobId")
                        .HasColumnType("text");

                    b.Property<int>("AttackMode")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("EndTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("HashType")
                        .HasColumnType("integer");

                    b.Property<float>("ProgressPercentage")
                        .HasColumnType("real");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("JobId");

                    b.ToTable("JobRecords");
                });
#pragma warning restore 612, 618
        }
    }
}
